### PR TITLE
Fix error when searching

### PR DESCRIPTION
**Pull request by einardivision**
I was getting an error when trying to search in the control panel, nova wanted to call undefined static property model, so by defining this value here you nullify and error and everything works.

### CODE REVIEW

**Comment by Nyratas** [comment]
Hi @einardivision,

Thanks for your pull-request!

I think the NovaPage Resource is potentially as important in the global search as other "model" Resources. Therefore, maybe we should make it available for search instead of disabling it. 

Honestly, I didn't try to make it work with the global search yet and that's why you're facing this issue. We should take a deeper look into it as soon as possible.

**Comment by einardivision** [comment]
Yeah i just wanted to put it here incase someone else was having troubles :)

**Comment by Nyratas** [comment]
Thanks a lot for that :)

**Comment by LasseHaslev** [comment]
I agree that the global search is relevant for the page resource as #15. But at this point this package is breaking the global search for every other nova resource.

Until the global search works with Page resources I suggest we disable it entierly.

```php
/**
 * Indicates if the resoruce should be globally searchable.
 *
 * @var bool
 */
public static $globallySearchable = false;
```

**Comment by voidgraphics** [comment]
@LasseHaslev I agree, and I just pushed a new release (`v0.2.1`) that does exactly what you suggested. Hopefully we can find some time to fix the search properly soon.

**Comment by LasseHaslev** [comment]
@voidgraphics it works! Thanks for quick response and great package!

**Pull request closed without merging**
