### PR TITLE
Adding empty $model propety to the main resource

### PR DESCRIPTION
**Pull request by shalawani**
According to integrate [laravel-auditing](https://github.com/owen-it/laravel-auditing) we should have $model property defined on the resource

### CODE REVIEW

**Comment by Nyratas** [comment]
Hi @shalawani,

Why set the model to an empty string? Is there an issue if `$model` is declared and defaults to `null`?

Thanks!

**Comment by shalawani** [comment]
Hi @Nyratas 
Yes there is an issue when integrating [laravel-auditing](https://github.com/owen-it/laravel-auditing) with your package

**Comment by Nyratas** [comment]
@shalawani that's what I understood from your first message. To be more precise, my question would be:

Is there still a problem with the integration of laravel-auditing if you set `$model` to `null`, as shown in this example:

```php
    public static $model;
```

Instead of declaring it as an empty string as you did:

```php
    public static $model = '';
```

?

**Comment by shalawani** [comment]
I think the issue was from another thing.

I tested it now without my change and it works ok, Sorry for wasting your time.

**Comment by Nyratas** [comment]
I'm glad you found a solution to your problem. Thanks for using NovaPage! ;)

**Pull request closed without merging**
